spring.application.name=Learnia
server.port=8088


spring.datasource.url=jdbc:mysql://localhost:3306/Learnia_db_in5bm?useSSL=false
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=adminroot
=======
spring.datasource.password=admin
>>>>>>> d82e2af8923c9a8ef5605c2317c2260c943339a9
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false
